// ============================================
// JuridIQ - Mock Data for Development
// ============================================

import type {
  Profile,
  Despacho,
  Cliente,
  Expediente,
  ExpedienteTarea,
  Cita,
  ConsultaIA,
  Notificacion,
} from '@/types/database';

// ---- Despacho ----
export const mockDespacho: Despacho = {
  despacho_id: 'd1a2b3c4-5678-9012-3456-789012345678',
  nombre_despacho: 'García, López & Asociados',
  email_principal: 'contacto@garcialopez.com.mx',
  telefono: '+52 55 1234 5678',
  direccion: 'Av. Reforma 505, Piso 12, Col. Cuauhtémoc',
  ciudad: 'Ciudad de México',
  plan: 'profesional',
  fecha_creacion: '2024-01-15T10:00:00Z',
  activo: true,
};

// ---- Profiles (Abogados) ----
export const mockProfiles: Profile[] = [
  {
    id: 'u1-admin-001',
    email: 'carlos.garcia@garcialopez.com.mx',
    nombre_completo: 'Lic. Carlos García Mendoza',
    role: 'admin_despacho',
    especialidad: 'penal',
    despacho_id: mockDespacho.despacho_id,
    telefono: '+52 55 9876 5432',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'u2-abogado-001',
    email: 'ana.lopez@garcialopez.com.mx',
    nombre_completo: 'Lic. Ana López Rivera',
    role: 'abogado',
    especialidad: 'civil',
    despacho_id: mockDespacho.despacho_id,
    telefono: '+52 55 8765 4321',
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'u3-abogado-002',
    email: 'miguel.ramirez@garcialopez.com.mx',
    nombre_completo: 'Lic. Miguel Ramírez Torres',
    role: 'abogado',
    especialidad: 'mercantil',
    despacho_id: mockDespacho.despacho_id,
    telefono: '+52 55 7654 3210',
    created_at: '2024-03-15T10:00:00Z',
  },
];

export const mockCurrentUser = mockProfiles[0];

// ---- Clientes ----
export const mockClientes: Cliente[] = [
  {
    cliente_id: 'c001',
    despacho_id: mockDespacho.despacho_id,
    nombre_completo: 'Juan Pérez Hernández',
    email: 'juan.perez@email.com',
    telefono: '+52 55 1111 2222',
    tipo_identificacion: 'RFC',
    numero_identificacion: 'PEHJ850101AB1',
    domicilio: 'Calle Hidalgo 45, Col. Centro, CDMX',
    notas_generales: 'Cliente referido por el Lic. Martínez. Caso de fraude fiscal.',
    abogado_asignado_id: 'u1-admin-001',
    fecha_registro: '2024-06-10T09:00:00Z',
    estado: 'activo',
    abogado: mockProfiles[0],
    expedientes_count: 2,
  },
  {
    cliente_id: 'c002',
    despacho_id: mockDespacho.despacho_id,
    nombre_completo: 'María del Carmen García Ruiz',
    email: 'maria.garcia@email.com',
    telefono: '+52 55 3333 4444',
    tipo_identificacion: 'CURP',
    numero_identificacion: 'GARM900215MDFRZ01',
    domicilio: 'Av. Universidad 1500, Del Valle, CDMX',
    notas_generales: 'Proceso de divorcio. Requiere custodia compartida.',
    abogado_asignado_id: 'u2-abogado-001',
    fecha_registro: '2024-07-20T14:30:00Z',
    estado: 'activo',
    abogado: mockProfiles[1],
    expedientes_count: 1,
  },
  {
    cliente_id: 'c003',
    despacho_id: mockDespacho.despacho_id,
    nombre_completo: 'Empresas Tecnológicas del Norte S.A. de C.V.',
    email: 'legal@etdnorte.com.mx',
    telefono: '+52 81 5555 6666',
    tipo_identificacion: 'RFC',
    numero_identificacion: 'ETN200301KL9',
    domicilio: 'Blvd. Constitución 2020, Monterrey, NL',
    notas_generales: 'Cliente corporativo. Múltiples contratos mercantiles.',
    abogado_asignado_id: 'u3-abogado-002',
    fecha_registro: '2024-08-05T11:00:00Z',
    estado: 'activo',
    abogado: mockProfiles[2],
    expedientes_count: 3,
  },
  {
    cliente_id: 'c004',
    despacho_id: mockDespacho.despacho_id,
    nombre_completo: 'Roberto Sánchez Morales',
    email: 'roberto.sanchez@email.com',
    telefono: '+52 55 7777 8888',
    tipo_identificacion: 'RFC',
    numero_identificacion: 'SAMR770512QR5',
    domicilio: 'Calle Madero 300, Col. Roma, CDMX',
    notas_generales: 'Demanda laboral contra su ex-empleador. Despido injustificado.',
    abogado_asignado_id: 'u2-abogado-001',
    fecha_registro: '2024-09-01T16:00:00Z',
    estado: 'activo',
    abogado: mockProfiles[1],
    expedientes_count: 1,
  },
  {
    cliente_id: 'c005',
    despacho_id: mockDespacho.despacho_id,
    nombre_completo: 'Laura Martínez Vega',
    email: 'laura.mv@email.com',
    telefono: '+52 55 9999 0000',
    tipo_identificacion: 'CURP',
    numero_identificacion: 'MAVL880630MDFRG07',
    domicilio: 'Av. Insurgentes Sur 1800, CDMX',
    notas_generales: 'Caso archivado. Resolución favorable.',
    abogado_asignado_id: 'u1-admin-001',
    fecha_registro: '2024-03-15T10:00:00Z',
    estado: 'archivado',
    abogado: mockProfiles[0],
    expedientes_count: 1,
  },
];

// ---- Expedientes ----
export const mockExpedientes: Expediente[] = [
  {
    expediente_id: 'e001',
    cliente_id: 'c001',
    despacho_id: mockDespacho.despacho_id,
    abogado_responsable_id: 'u1-admin-001',
    tipo_caso: 'fiscal',
    titulo: 'Fraude Fiscal - Pérez Hernández',
    descripcion_inicial: 'El cliente fue notificado de un crédito fiscal por parte del SAT por supuestas irregularidades en declaraciones del ejercicio 2022. Se requiere impugnar el crédito.',
    estado_caso: 'en_proceso',
    fecha_creacion: '2024-06-15T10:00:00Z',
    monto_demanda: 1500000,
    juzgado: 'Tribunal Federal de Justicia Administrativa - Sala Regional CDMX',
    numero_expediente: 'TFA/2024/1234',
    fecha_proxima_audiencia: '2026-05-10T11:00:00Z',
    cliente: mockClientes[0],
    abogado: mockProfiles[0],
  },
  {
    expediente_id: 'e002',
    cliente_id: 'c002',
    despacho_id: mockDespacho.despacho_id,
    abogado_responsable_id: 'u2-abogado-001',
    tipo_caso: 'familiar',
    titulo: 'Divorcio - García Ruiz vs García Ruiz',
    descripcion_inicial: 'Procedimiento de divorcio incausado. La cliente solicita guardia y custodia de dos menores, así como pensión alimenticia.',
    estado_caso: 'en_proceso',
    fecha_creacion: '2024-07-25T14:00:00Z',
    juzgado: 'Juzgado 15° Familiar - CDMX',
    numero_expediente: 'JF15/2024/5678',
    fecha_proxima_audiencia: '2026-04-28T09:00:00Z',
    cliente: mockClientes[1],
    abogado: mockProfiles[1],
  },
  {
    expediente_id: 'e003',
    cliente_id: 'c003',
    despacho_id: mockDespacho.despacho_id,
    abogado_responsable_id: 'u3-abogado-002',
    tipo_caso: 'mercantil',
    titulo: 'Incumplimiento de Contrato - ETN vs Proveedora Nacional',
    descripcion_inicial: 'El cliente demanda a Proveedora Nacional S.A. por incumplimiento de contrato de suministro. Monto reclamado: $3,200,000 MXN.',
    estado_caso: 'apertura',
    fecha_creacion: '2024-10-01T09:00:00Z',
    monto_demanda: 3200000,
    juzgado: 'Juzgado 3° de lo Mercantil - Monterrey',
    numero_expediente: 'JM3/2024/9012',
    fecha_proxima_audiencia: '2026-05-05T10:00:00Z',
    cliente: mockClientes[2],
    abogado: mockProfiles[2],
  },
  {
    expediente_id: 'e004',
    cliente_id: 'c004',
    despacho_id: mockDespacho.despacho_id,
    abogado_responsable_id: 'u2-abogado-001',
    tipo_caso: 'laboral',
    titulo: 'Despido Injustificado - Sánchez Morales',
    descripcion_inicial: 'Demanda por despido injustificado. El cliente laboró 8 años en la empresa. Se reclaman: salarios caídos, prima de antigüedad, vacaciones, aguinaldo proporcional.',
    estado_caso: 'en_proceso',
    fecha_creacion: '2024-09-05T16:30:00Z',
    monto_demanda: 450000,
    juzgado: 'Junta Local de Conciliación y Arbitraje - CDMX',
    numero_expediente: 'JLCA/2024/3456',
    fecha_proxima_audiencia: '2026-04-22T12:00:00Z',
    cliente: mockClientes[3],
    abogado: mockProfiles[1],
  },
  {
    expediente_id: 'e005',
    cliente_id: 'c005',
    despacho_id: mockDespacho.despacho_id,
    abogado_responsable_id: 'u1-admin-001',
    tipo_caso: 'penal',
    titulo: 'Defensa Penal - Martínez Vega',
    descripcion_inicial: 'La cliente fue acusada de fraude genérico. Se logró demostrar su inocencia en etapa de investigación.',
    estado_caso: 'archivado',
    fecha_creacion: '2024-03-20T10:00:00Z',
    fecha_cierre: '2024-08-15T10:00:00Z',
    juzgado: 'Juzgado de Control - CDMX',
    numero_expediente: 'JC/2024/7890',
    cliente: mockClientes[4],
    abogado: mockProfiles[0],
  },
];

// ---- Tareas de Expediente ----
export const mockTareas: ExpedienteTarea[] = [
  {
    tarea_id: 't001',
    expediente_id: 'e001',
    titulo: 'Presentar recurso de revocación ante SAT',
    descripcion: 'Elaborar y presentar recurso de revocación contra crédito fiscal.',
    fecha_limite: '2026-04-25T17:00:00Z',
    responsable_id: 'u1-admin-001',
    estado: 'en_progreso',
    prioridad: 'urgente',
    orden: 1,
    responsable: mockProfiles[0],
  },
  {
    tarea_id: 't002',
    expediente_id: 'e001',
    titulo: 'Recopilar estados de cuenta bancarios 2022',
    descripcion: 'Solicitar al cliente todos los estados de cuenta del periodo fiscal en cuestión.',
    fecha_limite: '2026-04-20T17:00:00Z',
    fecha_completada: '2026-04-18T14:00:00Z',
    responsable_id: 'u1-admin-001',
    estado: 'completada',
    prioridad: 'alta',
    orden: 2,
    responsable: mockProfiles[0],
  },
  {
    tarea_id: 't003',
    expediente_id: 'e002',
    titulo: 'Preparar alegatos para audiencia de custodia',
    fecha_limite: '2026-04-27T12:00:00Z',
    responsable_id: 'u2-abogado-001',
    estado: 'pendiente',
    prioridad: 'alta',
    orden: 1,
    responsable: mockProfiles[1],
  },
  {
    tarea_id: 't004',
    expediente_id: 'e003',
    titulo: 'Redactar demanda mercantil',
    descripcion: 'Elaborar escrito de demanda con todas las pruebas documentales.',
    fecha_limite: '2026-05-01T17:00:00Z',
    responsable_id: 'u3-abogado-002',
    estado: 'en_progreso',
    prioridad: 'alta',
    orden: 1,
    responsable: mockProfiles[2],
  },
  {
    tarea_id: 't005',
    expediente_id: 'e004',
    titulo: 'Calcular liquidación laboral',
    descripcion: 'Realizar cálculo detallado de prestaciones adeudadas.',
    fecha_limite: '2026-04-21T17:00:00Z',
    responsable_id: 'u2-abogado-001',
    estado: 'pendiente',
    prioridad: 'media',
    orden: 1,
    responsable: mockProfiles[1],
  },
];

// ---- Citas ----
const today = new Date();
const formatDate = (d: Date) => d.toISOString();

export const mockCitas: Cita[] = [
  {
    cita_id: 'ci001',
    despacho_id: mockDespacho.despacho_id,
    abogado_id: 'u1-admin-001',
    cliente_id: 'c001',
    fecha_hora: formatDate(new Date(today.getFullYear(), today.getMonth(), today.getDate(), 10, 0)),
    duracion_minutos: 60,
    titulo_asunto: 'Revisión de recurso fiscal',
    descripcion_cliente: 'Revisar avance del recurso de revocación y documentación faltante.',
    confirmada: true,
    enviado_recordatorio: true,
    tipo_cita: 'presencial',
    cliente: mockClientes[0],
    abogado: mockProfiles[0],
  },
  {
    cita_id: 'ci002',
    despacho_id: mockDespacho.despacho_id,
    abogado_id: 'u2-abogado-001',
    cliente_id: 'c002',
    fecha_hora: formatDate(new Date(today.getFullYear(), today.getMonth(), today.getDate(), 14, 30)),
    duracion_minutos: 45,
    titulo_asunto: 'Actualización caso divorcio',
    descripcion_cliente: 'Informar sobre la próxima audiencia y preparar documentos.',
    confirmada: true,
    enviado_recordatorio: false,
    tipo_cita: 'virtual',
    enlace_zoom: 'https://zoom.us/j/1234567890',
    cliente: mockClientes[1],
    abogado: mockProfiles[1],
  },
  {
    cita_id: 'ci003',
    despacho_id: mockDespacho.despacho_id,
    abogado_id: 'u3-abogado-002',
    cliente_id: 'c003',
    fecha_hora: formatDate(new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 11, 0)),
    duracion_minutos: 90,
    titulo_asunto: 'Firma de demanda mercantil',
    descripcion_cliente: 'Revisión final y firma de la demanda contra Proveedora Nacional.',
    confirmada: false,
    enviado_recordatorio: false,
    tipo_cita: 'presencial',
    cliente: mockClientes[2],
    abogado: mockProfiles[2],
  },
  {
    cita_id: 'ci004',
    despacho_id: mockDespacho.despacho_id,
    abogado_id: 'u2-abogado-001',
    cliente_id: 'c004',
    fecha_hora: formatDate(new Date(today.getFullYear(), today.getMonth(), today.getDate() + 2, 16, 0)),
    duracion_minutos: 60,
    titulo_asunto: 'Preparación audiencia laboral',
    descripcion_cliente: 'Preparar al cliente para la audiencia en la Junta de Conciliación.',
    confirmada: true,
    enviado_recordatorio: false,
    tipo_cita: 'telefonica',
    cliente: mockClientes[3],
    abogado: mockProfiles[1],
  },
  {
    cita_id: 'ci005',
    despacho_id: mockDespacho.despacho_id,
    abogado_id: 'u1-admin-001',
    cliente_id: undefined,
    fecha_hora: formatDate(new Date(today.getFullYear(), today.getMonth(), today.getDate() + 3, 9, 0)),
    duracion_minutos: 30,
    titulo_asunto: 'Consulta inicial - Nuevo prospecto',
    confirmada: false,
    enviado_recordatorio: false,
    tipo_cita: 'presencial',
    nombre_publico: 'Fernando Castillo',
    email_publico: 'fernando.c@email.com',
    telefono_publico: '+52 55 2345 6789',
    abogado: mockProfiles[0],
  },
];

// ---- Consultas IA ----
export const mockConsultasIA: ConsultaIA[] = [
  {
    consulta_id: 'q001',
    despacho_id: mockDespacho.despacho_id,
    abogado_id: 'u1-admin-001',
    pregunta_original: '¿Cuál es el plazo de prescripción para delitos fiscales en México?',
    respuesta_claude: `## Prescripción de Delitos Fiscales en México\n\nDe acuerdo con el **Código Fiscal de la Federación (CFF)**, los plazos de prescripción varían:\n\n### Plazo General\n- **5 años** para la mayoría de delitos fiscales (Art. 100 CFF)\n\n### Plazo Especial\n- **8 años** cuando el monto defraudado excede de $7,804,230.00 MXN\n- **Sin prescripción** para delitos de defraudación fiscal calificada\n\n### Base Legal\n- Artículo 100 del CFF\n- Artículo 108 del CFF (defraudación fiscal)\n- Tesis Aislada 2a./J. 12/2020\n\n> **Nota**: El plazo comienza a contar desde la comisión del delito o desde que la autoridad tuvo conocimiento.`,
    tokens_utilizados: 1250,
    tipo_consulta: 'ley',
    fecha_consulta: '2026-04-15T10:30:00Z',
    compartida_con_cliente: false,
    abogado: mockProfiles[0],
  },
  {
    consulta_id: 'q002',
    despacho_id: mockDespacho.despacho_id,
    abogado_id: 'u2-abogado-001',
    pregunta_original: '¿Qué criterios utiliza el juez para determinar la guardia y custodia de menores?',
    respuesta_claude: `## Criterios para Guardia y Custodia de Menores\n\nLos tribunales mexicanos consideran el **interés superior del menor** como principio rector:\n\n### Criterios Principales\n1. **Vínculo afectivo** con cada progenitor\n2. **Estabilidad emocional** del menor\n3. **Capacidad económica** de los padres\n4. **Entorno social** y escolar\n5. **Opinión del menor** (si tiene más de 12 años)\n\n### Marco Legal\n- Art. 4° Constitucional\n- Arts. 416-417 Código Civil Federal\n- Convención sobre los Derechos del Niño`,
    tokens_utilizados: 980,
    tipo_consulta: 'jurisprudencia',
    fecha_consulta: '2026-04-14T16:00:00Z',
    compartida_con_cliente: true,
    expediente_id: 'e002',
    abogado: mockProfiles[1],
  },
];

// ---- Notificaciones ----
export const mockNotificaciones: Notificacion[] = [
  {
    notificacion_id: 'n001',
    despacho_id: mockDespacho.despacho_id,
    usuario_id: 'u1-admin-001',
    tipo: 'cita_recordatorio',
    titulo: 'Cita en 1 hora',
    mensaje: 'Tienes una cita con Juan Pérez Hernández a las 10:00 AM',
    leida: false,
    canal: 'web',
    enviada: true,
    fecha_envio: formatDate(new Date()),
    fecha_creacion: formatDate(new Date()),
  },
  {
    notificacion_id: 'n002',
    despacho_id: mockDespacho.despacho_id,
    usuario_id: 'u1-admin-001',
    tipo: 'tarea_vencida',
    titulo: 'Tarea próxima a vencer',
    mensaje: 'La tarea "Presentar recurso de revocación" vence el 25 de abril.',
    leida: false,
    canal: 'web',
    enviada: true,
    fecha_envio: formatDate(new Date()),
    fecha_creacion: formatDate(new Date()),
  },
  {
    notificacion_id: 'n003',
    despacho_id: mockDespacho.despacho_id,
    usuario_id: 'u2-abogado-001',
    tipo: 'expediente_audiencia',
    titulo: 'Audiencia próxima',
    mensaje: 'El expediente "Divorcio - García Ruiz" tiene audiencia el 28 de abril.',
    leida: true,
    canal: 'web',
    enviada: true,
    fecha_envio: formatDate(new Date(Date.now() - 86400000)),
    fecha_creacion: formatDate(new Date(Date.now() - 86400000)),
  },
];

// ---- Stats para Dashboard ----
export const mockStats = {
  clientesActivos: mockClientes.filter(c => c.estado === 'activo').length,
  expedientesAbiertos: mockExpedientes.filter(e => e.estado_caso !== 'archivado').length,
  citasHoy: mockCitas.filter(c => {
    const citaDate = new Date(c.fecha_hora);
    return citaDate.toDateString() === today.toDateString();
  }).length,
  tareasVencidas: mockTareas.filter(t => t.estado === 'vencida').length,
  tareasPendientes: mockTareas.filter(t => t.estado === 'pendiente' || t.estado === 'en_progreso').length,
  consultasIA: mockConsultasIA.length,
  casosAbiertos: mockExpedientes.filter(e => e.estado_caso === 'apertura' || e.estado_caso === 'en_proceso').length,
  casosCerrados: mockExpedientes.filter(e => e.estado_caso === 'archivado' || e.estado_caso === 'sentenciado').length,
};
